package(default_visibility = ["//visibility:public"])

config_setting(
    name = "darwin_x64",
    values = {"host_cpu": "darwin_x64"},
)

config_setting(
    name = "darwin_arm64",
    values = {"host_cpu": "darwin_arm64"},
)

config_setting(
    name = "linux_arm64",
    values = {"host_cpu": "linux_arm64"}
)

config_setting(
    name = "linux_x64",
    values = {"host_cpu": "linux_x64"}
)

config_setting(
    name = "windows_x64",
    values = {"host_cpu": "windows_x64"}
)

config_setting(
    name = "coverage_config",
    values = {
        "collect_code_coverage": "true",
    },
)
